# Generated by Django 4.1.7 on 2023-02-19 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_acct_attribute_acct_classification_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="acct_classification",
        ),
    ]
