# Generated by Django 4.1.7 on 2023-02-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_acct_attribute_delete_acct_classification"),
    ]

    operations = [
        migrations.AddField(
            model_name="acct_attribute",
            name="address",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="acct_attribute",
            name="user",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="acct_attribute",
            name="phone",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
