# Generated by Django 4.1.7 on 2023-02-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_delete_acct_classification"),
    ]

    operations = [
        migrations.AddField(
            model_name="acct_attribute",
            name="address",
            field=models.CharField(default="", max_length=50),
        ),
    ]
