# Generated by Django 4.1.7 on 2023-02-18 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_acct_attribute_address_acct_attribute_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="acct_attribute",
            name="address",
        ),
        migrations.RemoveField(
            model_name="acct_attribute",
            name="gender",
        ),
    ]
