# Generated by Django 4.1.7 on 2023-02-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_acct_attribute_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acct_attribute",
            name="user",
            field=models.IntegerField(default=1),
        ),
    ]
