# Generated by Django 4.1.7 on 2023-02-19 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(max_length=20)),
                ("user", models.IntegerField(default=1)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "rootid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.acct_attribute",
                    ),
                ),
            ],
        ),
    ]
