# Generated by Django 4.1.7 on 2023-02-18 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_acct_attribute"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acct_attribute",
            name="rootid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="account.acct_classification",
            ),
        ),
    ]
