# Generated by Django 4.1.7 on 2023-02-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_alter_staff_position"),
    ]

    operations = [
        migrations.CreateModel(
            name="enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rootid", models.IntegerField()),
                ("staff_id", models.IntegerField()),
                ("class_id", models.IntegerField()),
                ("data_from", models.DateField()),
                ("user", models.IntegerField(default=1)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
