# Generated by Django 4.1.7 on 2023-02-19 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0010_alter_enrollment_rootid"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("None Active", "None Active"),
                    ("Suspended", "Suspended"),
                ],
                default="Active",
                max_length=20,
            ),
        ),
    ]
