# Generated by Django 4.1.7 on 2023-02-19 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0012_classname_alter_enrollment_class_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classname",
            name="name",
            field=models.CharField(default="", max_length=30),
        ),
    ]
