# Generated by Django 4.1.7 on 2023-02-19 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0014_alter_classname_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="subjectName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("English", "English"),
                            ("Mathmatics", "Mathmatics"),
                            ("History", "History"),
                            ("Shona", "Shona"),
                        ],
                        default="",
                        max_length=30,
                    ),
                ),
                ("user", models.IntegerField(default=1)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "rootid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.acct_attribute",
                    ),
                ),
            ],
        ),
    ]
