# Generated by Django 4.1.7 on 2023-02-20 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0016_transcript"),
    ]

    operations = [
        migrations.RenameField(
            model_name="enrollment",
            old_name="data_from",
            new_name="date_from",
        ),
        migrations.CreateModel(
            name="fees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Fully Paid", "Fully Paid"),
                            ("Patially Paid", "Patially Paid"),
                            ("Not Paid", "Not Paid"),
                        ],
                        default="Active",
                        max_length=20,
                    ),
                ),
                ("paid_date", models.DateField()),
                ("user", models.IntegerField(default=1)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "class_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.classname",
                    ),
                ),
                (
                    "enrollment_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.enrollment",
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.student",
                    ),
                ),
            ],
        ),
    ]
