# Generated by Django 4.1.7 on 2023-02-20 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0017_rename_data_from_enrollment_date_from_fees"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fees",
            name="status",
            field=models.CharField(
                choices=[
                    ("Fully Paid", "Fully Paid"),
                    ("Partially Paid", "Partially Paid"),
                    ("Not Paid", "Not Paid"),
                ],
                default="Active",
                max_length=20,
            ),
        ),
    ]
