# Generated by Django 4.1.7 on 2023-02-20 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0018_alter_fees_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="fees",
            name="amount",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
