# Generated by Django 4.1.7 on 2023-02-20 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="acct_attribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("Student", "Student"),
                            ("Teacher", "Teacher"),
                            ("Staff", "Staff"),
                            ("Parent", "Parent"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("Female", "Female"), ("Male", "Male")], max_length=20
                    ),
                ),
                ("phone", models.IntegerField()),
                ("address", models.CharField(default="", max_length=50)),
                ("user", models.IntegerField(default=1)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "rootid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="className",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Form 1 - Blue", "Form 1 - Blue"),
                            ("Form 1 - Red", "Form 1 - Red"),
                            ("Form 1 - Green", "Form 1 - Green"),
                            ("Form 2 - Blue", "Form 2 - Blue"),
                            ("Form 2 - Red", "Form 2 - Red"),
                            ("Form 2 - Green", "Form 2 - Green"),
                        ],
                        default="",
                        max_length=30,
                    ),
                ),
                ("teacher_id", models.IntegerField()),
                ("user", models.IntegerField(default=1)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staff_id", models.IntegerField()),
                ("date_from", models.DateField()),
                ("user", models.IntegerField(default=1)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "class_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="acct.classname"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dob", models.DateField()),
                ("parent_id", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("None Active", "None Active"),
                            ("Suspended", "Suspended"),
                        ],
                        default="Active",
                        max_length=20,
                    ),
                ),
                ("user", models.IntegerField(default=1)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "rootid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="acct.acct_attribute",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="subjectName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("English", "English"),
                            ("Mathmatics", "Mathmatics"),
                            ("History", "History"),
                            ("Shona", "Shona"),
                        ],
                        default="",
                        max_length=30,
                    ),
                ),
                ("user", models.IntegerField(default=1)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "rootid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="acct.acct_attribute",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="transcript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mark", models.CharField(max_length=10)),
                ("grade", models.CharField(max_length=20)),
                ("teacher_comments", models.CharField(max_length=100)),
                ("user", models.IntegerField(default=1)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "class_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="acct.classname"
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="acct.student"
                    ),
                ),
                (
                    "subject_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="acct.subjectname",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("Headmaster", "Headmaster"),
                            ("Teacher", "Teacher"),
                            ("Administrator", "Administrator"),
                        ],
                        max_length=20,
                    ),
                ),
                ("user", models.IntegerField(default=1)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "rootid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="acct.acct_attribute",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="fees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Fully Paid", "Fully Paid"),
                            ("Partially Paid", "Partially Paid"),
                            ("Not Paid", "Not Paid"),
                        ],
                        default="Active",
                        max_length=20,
                    ),
                ),
                ("paid_date", models.DateField()),
                ("user", models.IntegerField(default=1)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "class_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="acct.classname"
                    ),
                ),
                (
                    "enrollment_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="acct.enrollment",
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="acct.student"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="enrollment",
            name="rootid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="acct.student"
            ),
        ),
    ]
