# Generated by Django 4.1.7 on 2023-02-24 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("acct", "0002_alter_student_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="parent_id",
        ),
        migrations.CreateModel(
            name="Parent",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("dob", models.DateField()),
                ("user", models.IntegerField(default=1)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "rootid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="acct.acct_attribute",
                    ),
                ),
            ],
        ),
    ]
