# Generated by Django 4.1.7 on 2023-02-24 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("acct", "0003_remove_student_parent_id_parent"),
    ]

    operations = []
