# Generated by Django 4.1.7 on 2023-02-24 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("acct", "0004_auto_20230224_1556"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parent",
            name="dob",
        ),
        migrations.AddField(
            model_name="student",
            name="parent",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="acct.parent"
            ),
        ),
    ]
