# Generated by Django 4.1.7 on 2023-02-24 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("acct", "0005_remove_parent_dob_student_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="parent",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="acct.parent"
            ),
        ),
    ]
