# Generated by Django 4.1.7 on 2023-02-24 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("acct", "0008_remove_student_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="parent",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="acct.parent"
            ),
            preserve_default=False,
        ),
    ]
