# Generated by Django 4.1.7 on 2023-02-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acct", "0010_remove_student_parent_alter_acct_attribute_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="parent",
            name="students",
            field=models.ManyToManyField(to="acct.student"),
        ),
        migrations.AlterField(
            model_name="parent",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
