# Generated by Django 4.1.7 on 2023-02-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acct", "0011_parent_students_alter_parent_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="position",
            field=models.CharField(
                choices=[
                    ("Headmaster", "Headmaster"),
                    ("Administrator", "Administrator"),
                ],
                max_length=20,
            ),
        ),
    ]
