# Generated by Django 4.1.7 on 2023-02-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acct", "0012_alter_staff_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="position",
            field=models.CharField(
                choices=[
                    ("Headmaster", "Headmaster"),
                    ("Teacher", "Teacher"),
                    ("Administrator", "Administrator"),
                ],
                max_length=20,
            ),
        ),
    ]
