# Generated by Django 4.1.7 on 2023-03-01 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("acct", "0014_subject_teaches_staff_teach_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classname",
            name="teacher_id",
        ),
        migrations.AddField(
            model_name="classname",
            name="class_teacher",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="acct.staff"
            ),
            preserve_default=False,
        ),
    ]
