# Generated by Django 4.1.7 on 2023-03-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acct", "0017_rename_student_id_transcript_student_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classname",
            name="user",
        ),
        migrations.RemoveField(
            model_name="fees",
            name="user",
        ),
        migrations.RemoveField(
            model_name="transcript",
            name="user",
        ),
        migrations.AddField(
            model_name="classname",
            name="subject",
            field=models.ManyToManyField(to="acct.subject"),
        ),
        migrations.AlterField(
            model_name="classname",
            name="id",
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="classname",
            name="name",
            field=models.CharField(max_length=30),
        ),
    ]
